### ISSUE TITLE
Invalid access to checksum protected area  below 0x80

### ISSUE THREAD

**Issue by Jacob-Burckhardt** [richardeoin/ftx-prog#16]
`ftx_prog --old-serial-number DN00X61S --product ThumbDV`

said:

```
Rewriting eeprom with new contents.
ftdi_write_eeprom_location() failed: Invalid access to checksum protected area  below 0x80

```
https://github.com/richardeoin/ftx-prog/blob/master/ftx_prog.c

says:

```
	for (i = 0; i < len/2; i++) {
		if (ftdi_write_eeprom_location(&ftdi, i,
eeprom[i*2] | (eeprom[(i*2)+1] << 8))) {

```
Note that variable _i_ starts as 0 and it passes _i_ in the second argument to ftdi_write_eeprom_location, but that argument is not allowed to be less than 0x80 according to:

http://developer.intra2net.com/git/?p=libftdi;a=blob_plain;f=src/ftdi.c;hb=HEAD

which says:

```
int ftdi_write_eeprom_location(struct ftdi_context *ftdi, int eeprom_addr,
                               unsigned short eeprom_val)
{
    int chip_type_location;
    unsigned short chip_type;

    if (ftdi == NULL || ftdi->usb_dev == NULL)
        ftdi_error_return(-2, "USB device unavailable");

    if (eeprom_addr <0x80)
        ftdi_error_return(-2, "Invalid access to checksum protected area  below 0x80");

```
That occurred with a ThumbDV device that has a FTDI chip.  If you want more info on ThumbDV, see:

http://nwdigitalradio.com/thumbdv-and-dv3000-resource-page/

**Comment by ambrice** [comment]
I also saw this problem when using ftx_prog compiled against recent (1.3) litbftdi.  Debian also had an older libftdi package (0.20), and when I compiled ftx_prog against that version this problem "went away".  Not sure if that's good or bad, but device seems to work.

**Comment by JanFeld** [comment]
This still is an issue today.
Am i right when i say it's most likely an libftdi-issue?
Or are there any fixes yet?
